Document: hddmonitor-udpserver
Title: Debian hddmonitor-udpserver Manual
Author: <insert document author here>
Abstract: This manual describes what hddmonitor-udpserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hddmonitor-udpserver/hddmonitor-udpserver.sgml.gz

Format: postscript
Files: /usr/share/doc/hddmonitor-udpserver/hddmonitor-udpserver.ps.gz

Format: text
Files: /usr/share/doc/hddmonitor-udpserver/hddmonitor-udpserver.text.gz

Format: HTML
Index: /usr/share/doc/hddmonitor-udpserver/html/index.html
Files: /usr/share/doc/hddmonitor-udpserver/html/*.html
